### ISSUE TITLE
Remove mandatory requirement for LDAP

### ISSUE THREAD

**Issue by lbeltrame** [digicoop/kaiwa#18]
I already have a LDAP server (389-ds) and it serves another purpose: all users on my Prosody server are not in LDAP.

Currently you seem to be forced to use LDAP.

**Comment by warcode** [comment]
You can remove the LDAP entry from packages.config, remove the ldap section from the config and empty the LDAP import in server.js.

Its optional, but not easily disabled.

**Comment by afics** [comment]
+1

**Comment by the-solipsist** [comment]
As a more general request, allowing severability in the software for those who already have the XMPP server + authentication mechanism running, and want Kaiwa as a web + MUC interface.

**Comment by sgologuzov** [comment]
I wanted to use Kaiwa with my Prosody server which has own external authentication. But I cannot use it due the LDAP required.

**Comment by ailin-nemui** [comment]
you can simply remove the `"ldap":{}` block from the config if you're not too worried about the dependency of the ldap library (which won't hurt even if you don't use it)

**Comment by sebu77** [comment]
you can simply remove the "ldap":{}
The dependency has been removed

**Comment by tristan-k** [comment]
> You can remove the LDAP entry from packages.config, remove the ldap section from the config and empty the LDAP import in server.js.

I did that, but now there are several other problems: There are no contacts anymore and connection problems.

**Comment by MurzNN** [comment]
@tristan-k did you solve the problem with contacts without LDAP server? Or find any workaround?

**Comment by tristan-k** [comment]
@MurzNN I did not.
