### ISSUE TITLE
kaiwa vs otalk

### ISSUE THREAD

**Issue by flosse** [digicoop/kaiwa#2]
could you add some notes to the readme about the differences between the original code and the fork? Or just mention the reason for the fork.
thx.

**Comment by devurandom** [comment]
Same issue here, plus some confusion: Kaiwa's readme says "Kaiwa is a fork of otalk by &yet". The [otalk website](http://otalk.org/) says, that otalk is also by &yet. Why does @andyet fork its own product and then ship it under a new name?

**Comment by sebu77** [comment]
The readme has been updated. More information on the &yet blog: http://blog.andyet.com/2015/04/08/kaiwa-otalk

**Comment by devurandom** [comment]
So otalk still exists, @andyet only passed the maintenance of the talk.im component to @digicoop, who know call that component Kaiwa?
