### ISSUE TITLE
One Click Deploy to DigitalOcean does not work!

### ISSUE THREAD

**Issue by the4ndy** [digicoop/kaiwa#23]
I used the "Deploy on DIgitalOcean" button on your website "getkaiwa.com" and I have tried it 3 times now and despite that I never get past the page that says 
"Your Droplet was successfully deployed
The IP address of your Droplet is <IPADDRESSS>
It may take up to 15 minutes for the server to be finalized. Refresh your browser until the Kaiwa website loads."

From there, nothing ever changes / happens. I updated my DNS and tried to navigate directly to the IP, connection refused. 

Please advised how to resolve this. I would have maybe looked around on your forums or a community help section but one does not exist that I can tell.

**Comment by pabloalbrecht** [comment]
Same here, it's been 30 minutes, will try again tomorrow but it seems long

**Comment by pabloalbrecht** [comment]
Apparently, if you setup a cheap 5$/month node, the server wouldn't start, but if you start with the ones at 10$/month, it runs perfectly (so far) and loads quickly. Hope this solves your problem the4ndy

**Comment by pabloalbrecht** [comment]
It seems that Amsterdam2 is working but none of the other locations

**Comment by thejae** [comment]
![Use Top to see](http://i61.tinypic.com/2h85r3n.jpg)

I used 'Top' to monitor the install progress and even after docker.io has stopped, my host wouldn't respond to HTTP requests. Waited for 2 hours before rebooting. Reboot also doesnt work.

Dropplet specs:
1GB Ram 30GB SSD Disk Singapore 1 Ubuntu 14.04 x64

**Comment by aleksandrbogdanov** [comment]
Also does not work for me on a 5$ Droplet, but on a 10$ it does.

I guess docker just can't finish provisioning.

**Comment by lorenz** [comment]
Just did it on a 8GB one (FRA1), worked after 9 minutes. Is expensive but for testing it still costs you some 0.2$.

**Comment by sebu77** [comment]
It should be ok with the $10 droplet
