### ISSUE TITLE
gitignore config file

### ISSUE THREAD

**Issue by thefinn93** [digicoop/kaiwa#24]
Maybe I'm just missing it, but there doesn't seem to be a way to change any configuration without editing `dev_config.json`, which then breaks `git pull`, and might get accidently committed. Is there a way to specify a different config file? Ideally, the one provided in git called like `dev_config.example.json`, then copy it to `dev_config.json` to configure the server, and have `dev_config.json` listed in `.gitignore`

**Comment by ailin-nemui** [comment]
`NODE_ENV=xxx node server`

**Comment by nils-werner** [comment]
PR #43 should fix this.

**Comment by sebu77** [comment]
Resolved with PR #43
