### ISSUE TITLE
Unhandled c2s stanza: iq; xmlns=urn:xmpp:mam:tmp

### ISSUE THREAD

**Issue by teodor-pripoae** [digicoop/kaiwa#28]
I'm using latest version of `mod_mam` on prosody and I'm seeing this error in logs.

```
stanzarouter                              debug	Unhandled c2s stanza: iq; xmlns=urn:xmpp:mam:tmp
```

You can see on `mod_mam` page that `XEP-0313` has changed.

https://code.google.com/p/prosody-modules/wiki/mod_mam

I think this was already fixed for stanza.io: https://github.com/otalk/stanza.io/issues/42

**Comment by manwe-pl** [comment]
+1 on this

Any chances for switching to stanza.io 7.x?

**Comment by sebu77** [comment]
Switching to stanza.io 7.x is planned

**Comment by sebu77** [comment]
Kaiwa now uses stanza.io 7
