### ISSUE TITLE
Requirements (LDAP and others)

### ISSUE THREAD

**Issue by warcode** [digicoop/kaiwa#4]
Requires an install of the openldap libs before running npm install or it will fail.

Requesting that you list the full set of libs to install before running this so we don't have to re-run it repeatedly to figure it out during install.

**Comment by thefinn93** [comment]
On an Ubuntu 14.04 system, I had to install `libldap2-dev` and `uuid-dev` before it would budge.

**Comment by rschulman** [comment]
The LDAP lib also doesn't compile on node 12 yet, so kaiwa is not compatible with node 12 (unless there's a way to tell it not to use LDAP because my prosody server is already set up with users).

**Comment by plessbd** [comment]
to get this to build on CentOS
{code}
sudo yum install openldap-devel openldap libuuid-devel libicu-devel
{code}

**Comment by sebu77** [comment]
libldap2-dev is no longer required. The readme has been updated
