### ISSUE TITLE
REQUEST: Deploy as Chrome Application to use with existing XMPP server

### ISSUE THREAD

**Issue by stevenroose** [digicoop/kaiwa#46]
I only recently discovered Kaiwa and I'd really like to give it a try. However, it seems like Kaiwa only ships as the complete server + ldap + client package. 

It seems to be discouraged to use Kaiwa with your existing Jabber server.

So I'd like to request a deployment of Kaiwa as a Chrome App, so that it can be used as a Chrome-based Jabber client for any server. It should even be possible to make Kaiwa work offline.

**Comment by the-solipsist** [comment]
This is a great idea!

**Comment by sebu77** [comment]
Kaiwa is a xmpp client. It should work with any xmpp server. It doesn't need LDAP to work.
Kaiwa-server (https://github.com/digicoop/kaiwa-server) is a Prosody instance already configured.

**Comment by stevenroose** [comment]
@sebu77 I don't think you understand the request. It is exactly because Kaiwa should work with any XMPP server, it could be deployed as a Chrome Application, making it much more accessible.

**Comment by sebu77** [comment]
It was an answer to "However, it seems like Kaiwa only ships as the complete server + ldap + client package".
The Chrome app is a good idea. Maybe later.
