### ISSUE TITLE
How to turn on https for kaiwa? 

### ISSUE THREAD

**Issue by pan1c** [digicoop/kaiwa#53]
Hello, there is my config:
 cat dev_config.json 
{
    "isDev": true,
    "http": {
        "baseUrl": "https://jabber.mydomain.com:8000",
        "port": 8000,
        "key": "/etc/CERT/mydomain.com.key",
        "cert": "/etc/CERT/mydomain.com.crt"
    },
.....

But chrome show ERR_CONNECTION_CLOSED when i trying to open https://jabber.mydomain.com:8000

But http://jabber.mydomain.com:8000 (without S) works fine.

How i can switch on https? How i can debug this issue?

**Comment by andersruneson** [comment]
Maybe you could use a proxy like apache or nginx for https?

**Comment by pan1c** [comment]
Of course i can.
But when i see "key": and "cert": options in some config file I always suggest that https must work without proxies :)

**Comment by sammcj** [comment]
The config file seems to have no documentation anywhere so that probably doesn't help. Perhaps we should track another issue for creating some documentation?

**Comment by the-solipsist** [comment]
@pan1c Any luck with this?  If yes, could you share your apache/nginx site-config file?

**Comment by sebu77** [comment]
These options (now removed) have been inherited from Otalk. You could use a proxy like nginx for https.
