### ISSUE TITLE
Can't create digital ocean droplet

### ISSUE THREAD

**Issue by phillip-white-sociomantic** [digicoop/kaiwa#56]
Hey Guys,

The Digital ocean page fails with "Failed to create the droplet". Any ideas?

**Comment by bmcgonag** [comment]
So, my creation on Digital Ocean seemed to work, and I got the next page that said configuration may take up to 15 minutes.  

i refreshed as requested, and even went directly to the DO ip address, but Kaiwa never loaded.

The point being DO deployment worked, and I had a droplet, but never got Kaiwa to come up.  

I'm about to try again, and we'll see how it goes.

**Comment by bmcgonag** [comment]
Just as an update, the deployment worked again, but still (after 30 minutes of waiting), the Kaiwa page that says refresh won't load, nor will the DO IP entered directly into browser.  So deployment appears to work (at least a droplet is created).  

I'll create a new issue about not being able to get Kaiwa page to load after deployment.

**Comment by rjsteinert** [comment]
How did you guys set that up? Is there a place on Digital Ocean to produce that form?
