### ISSUE TITLE
Monal not open source

### ISSUE THREAD

**Issue by andersruneson** [digicoop/kaiwa#6]
http://getkaiwa.com/ states that Monal is open source:
"Unfortunately, the XMPP landscape on iOS is pretty bad. Monal is the only client still maintained and usable although it's still lacking. No support for chat syncing or message history. However, Monal is Open Source! "

But Monal is not open source. http://en.wikipedia.org/wiki/Monal_%28software%29

Thanks

**Comment by sebu77** [comment]
Monal description fixed. Thanks
