### ISSUE TITLE
new xmpp websocket rfc spec ~ stanza.io outdated

### ISSUE THREAD

**Issue by Bl4ckM** [digicoop/kaiwa#60]
Your dep stanza.io is outdated. New version is 7.3.5. That version is compatible with final xmpp over websocket rfc document. Openfire XMPP/Prosody Websocket Plugin use the final rfc standard for their XMPP Protocol Implementation. Kaiwa won't function properly anymore. Using the newest version of stanza.io in package.json leading to a broken and unable to connect kaiwa app. Could you fix your Code that it is possible to use it with the latest RFC XMPP over Websocket specification?

**Comment by the-solipsist** [comment]
@Bl4ckM: So does Kaiwa work right now? I'm on Prosody 0.10 nightly build 165.

**Comment by Bl4ckM** [comment]
yep all went right :) btw. kaiwa is working with openfire and websocket plugin as well. AND you need to add login.name@servername <- to login with kaiwa, you forked and changed the login placeholder... i just looked ahead to otalk and saw this little mistake :)

**Comment by xnuxer** [comment]
Unfortunately, I am still failed to connect kaiwa with openfire and websocket plugin, also haproxy. Do you have manual document/wiki to connect kaiwa with openfire?

**Comment by Bl4ckM** [comment]
kaiwa is a otalk fork. otalk uses stanza.io library. Just get into the stanza.io library, npm install & compile all, than you should be able to try the stanza.io demo client. Change your web dir to the demo client path. Use this sample client to try to connect to your Openfire Service. If you get the right parameters and can connect yourself with the demo client, you could also use these params to connect with otalk/kaiwa. The dome client is usefull because it prints all the communication between server and your demo client. Hope it could help you to find your problem :)

**Comment by sebu77** [comment]
I'm working on updating stanza.io. It was harder than just using the new version but it's almost done.
I will make a release this week.

**Comment by sebu77** [comment]
The Kaiwa code now uses stanza.io 7

**Comment by SEJeff** [comment]
@Bl4ckM Do you use a stable released version of openfire, or one of the development snapshots?
