### ISSUE TITLE
WebSocket opening handshake was canceled

### ISSUE THREAD

**Issue by Nomad145** [digicoop/kaiwa#68]
Greetings,

I have a Kaiwa server running alongside a Prosody server (version 0.10) and I am receiving the following error in Google Chrome on Linux (version 44.0.2403.125) with debugging enabled.

[5675:5675:1028/194711:INFO:CONSOLE(52753)] "WebSocket connection to 'wss://mydomain.net:5281/xmpp-websocket/' failed: WebSocket opening handshake was canceled", source: http://mydomain.net:8000/app.nonCached.js (52753)

The error occurs after attempting to log into the server.  I have accepted the certificate and I have even added the certificate in manually to the Authorities list within Chrome.  The server works fine in Firefox, but does not work on any version of Chrome I have tested so far.  Any help would be appreciated!

**Comment by stevenroose** [comment]
@Nomad145 Did you get this to work?

**Comment by Nomad145** [comment]
If I recall, I never got it to work properly in that version of Chrome.  I ended up purchasing a signed SSL cert and it solved the issue if I remember correctly.
